server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/a_test_database?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url: jdbc:mysql://localhost:3306/a_test_database?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: 123456
      users-center:
        # 用户中心数据库
        enabled: false
        url: jdbc:mysql://localhost:3306/user_center_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
      users-center-ods:
        # 用户中心ods数据库
        enabled: false
        url: jdbc:mysql://localhost:3306/user_center_ods_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
      expert:
        # 专家数据库
        enabled: false
        url: jdbc:mysql://localhost:3306/kjzj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    # Redis服务器的主机地址
    host: 127.0.0.1
    # Redis服务器的端口号
    port: 6379
    # 访问Redis服务器的密码
    password:
    # Redis数据库的索引
    database: 0
    # 连接Redis服务器的超时时间
    timeout: 2000


# 存储服务
fileOperator:
  service: obs
  minio:
    #Minio服务所在地址
    endpoint: http://172.16.115.19:9000
    #存储桶名称
    bucketName: xmgl
    #访问的key
    accessKey: dsep
    #访问的秘钥
    secretKey: kjj@8UF8V3DIQd
    #mnio url
    showUrl: https://zhgg.csti.cn/oss/${minio.bucketName}/
  oss:
    endpoint: 100.125.2.4:443
    accessKey: 0TTGO6O61405AUE0QAIK
    secretKey: kPNgm4nfkDdgyhoK3Yv9tUo4OdtX6dWdBFdZxxcX
    bucketName: cqkjj-guanlixitongceshi
    gatewayUrl: https://xmgltest.csti.cn/gateway/